sudo: false

env:
  - TERM=dumb
  
matrix:
    include:
    - os: linux
      language: java
      jdk:  openjdk8
    - os: linux
      language: java
      jdk:  openjdk11
    - os: linux
      language: java
      jdk:  openjdk12
    - os: linux
      language: java
      jdk:  openjdk-ea
    allow_failures:
       - os: linux
         language: java
         jdk:  openjdk-ea

#cache:
#  ccache: true
#  directories:
#  - /Users/travis/build/miho/

# before_script:
# - echo 'before script'
  
script:
  - export CWD=$(pwd)
  - cd core
  - sh ./gradlew clean publishToMavenLocal
  - cd $CWD
  - cd gradle-plugin
  - sh ./gradlew clean publishToMavenLocal
  - cd $CWD
  - cd test-suite
  - travis_wait 30 ./gradlew clean test
  - cd $CWD
